# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - ghfgfhgfghfgfhgf

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    
          
steps:
   - uses: actions/checkout@v4
   - uses: actions/setup-java@v3
     with:
      java-version: '17'
      distribution: 'temurin'
   - name: Build with Gradle
      run:./gradlew build
   - uses: actions/upload-artifact@v4
     with:
      name: Package
      path: build/libs 
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4471F30DE6BC470E96383F16F0E1DAA6 }}
